apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-crud.yml --controller deployment --volumes persistentVolumeClaim
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: delete
  name: delete
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8089
  selector:
    io.kompose.service: delete
