FROM eclipse-temurin:17-jdk-jammy

RUN apt-get update && apt-get install -y curl

WORKDIR /app

COPY ./build/libs/delete-0.0.1-SNAPSHOT.jar delete.jar

ENTRYPOINT ["java", "-jar", "delete.jar"]

EXPOSE 8089