FROM eclipse-temurin:17-jdk-jammy

RUN apt-get update && apt-get install -y curl

WORKDIR /app

COPY ./build/libs/gateway-0.0.1-SNAPSHOT.jar gateway.jar

ENTRYPOINT ["java", "-jar", "gateway.jar"]

EXPOSE 8080