FROM eclipse-temurin:17-jdk-jammy

RUN apt-get update && apt-get install -y curl

WORKDIR /app

COPY ./build/libs/get-0.0.1-SNAPSHOT.jar get.jar

ENTRYPOINT ["java", "-jar", "get.jar"]

EXPOSE 8086

# 맥에서 이미지 빌드 시
# docker buildx build --platform linux/amd64 -t crud-get -f dockerfile .