# 1. build stage
FROM gradle:8.10.1-jdk17 AS builder
WORKDIR /app
COPY . .
RUN ./gradlew clean build -x test

# 2. runtime stage
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=builder /app/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]

# 맥에서 이미지 빌드 시
# docker buildx build --platform linux/amd64 -t crud-get -f dockerfile .