FROM eclipse-temurin:17-jdk-jammy

RUN apt-get update && apt-get install -y curl

WORKDIR /app

COPY ./build/libs/post-0.0.1-SNAPSHOT.jar post.jar

ENTRYPOINT ["java", "-jar", "post.jar"]

EXPOSE 8087